//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatorioAtividades.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\DbRegistroAtividade." +
            "sdf.mdf;Integrated Security=True;Connect Timeout=30")]
        public string DbRegistroAtividade_sdfConnectionString {
            get {
                return ((string)(this["DbRegistroAtividade_sdfConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\"C:\\Users\\LFelipe\\Documents\\Visual Studio 2013\\Projects\\RelatorioAtiv" +
            "idadesControleTempo\\BancoDados\\DbRegistroAtividade.sdf\"")]
        public string DbRegistroAtividadeConnectionString {
            get {
                return ((string)(this["DbRegistroAtividadeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\"C:\\Users\\FELIPE\\OneDrive\\Projetos\\Visual Studio 2013\\Projects\\Relato" +
            "rioAtividadesControleTempo\\BancoDados\\DbRegistroAtividade.sdf\"")]
        public string DbRegistroAtividadeConnectionString1 {
            get {
                return ((string)(this["DbRegistroAtividadeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\"C:\\Users\\FELIPE\\OneDrive.old\\Projetos\\Visual Studio 2013\\Projects\\Re" +
            "latorioAtividadesControleTempo\\BancoDados\\DbRegistroAtividade.sdf\"")]
        public string DbRegistroAtividadeConnectionString2 {
            get {
                return ((string)(this["DbRegistroAtividadeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\DbRegistroAtividade.sdf")]
        public string DbRegistroAtividadeConnectionString3 {
            get {
                return ((string)(this["DbRegistroAtividadeConnectionString3"]));
            }
        }
    }
}
